# Setups
format = """\
[╭╴](#DADEDF)$directory$git_branch$character\
$all[╰─ ](#DADEDF)"""
right_format = """$git_status$cmd_duration"""
add_newline = true

# Prompt symbols
[character]
success_symbol = "[](#8EC07C bold)"
error_symbol = "[](#AD685A)"
vicmd_symbol = "[](#DD8F6E)"

[directory]
format = "[]($style)[ ](bg:#312C2E fg:#DD8F6E)[$path](bg:#312C2E fg:#83A598 bold)[ ]($style)"
style = "bg:none fg:#312C2E"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:#312C2E fg:#8EC07C bold)$branch](bg:#312C2E fg:#83A598)[ ]($style)"
style = "bg:none fg:#312C2E"

[git_status]
format = "[]($style)[$all_status$ahead_behind](bg:#312C2E fg:#b4befe)[ ]($style)"
style = "bg:none fg:#312C2E"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = "󰄬"
untracked = "?${count}"
stashed = "󰏖"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[cmd_duration]
min_time = 1
format = "[]($style)[[ ](bg:#312C2E fg:#eba0ac bold)$duration](bg:#312C2E fg:#BBC3DF)[ ]($style)"
disabled = false
style = "bg:none fg:#312C2E"


# Override unrecognized icon
[php]
format = 'via [ $version](147 bold) '

[docker_context]
format = 'via [ $context](blue bold)'

[dart]
format = 'via [ $version](bold red) '

[golang]
format = 'via [ $version](bold cyan) '

[lua]
format = 'via [󰽥 $version](bold blue) '

[python]
symbol = " "
python_binary = "python3"

[rlang]
format = 'with [ $version](blue bold) '

[rust]
format = 'via [ $version](red bold)'



